#==================#
#    ExPickaxes    #
#  ver GabeZillia  #
#   ArcticRaven_   #
#==================#

options:
	#This sets the maximum amout of blocks the pickaxes can break
	EpickMaxHealth : 1561
	
	#These set the thresholds for the notifications, by setting thier value above the EpickMaxHealth value, they will be removed
	EpickNotif1 : 1400
	EpickNotif2 : 1500
	
	#This will enable the explosion effect for ALL players, also plays the explosion sound
	ExpickEffect : true
	
command ExPick <player=%player%>:
	usage: /expick <player>
	aliases: ExPick
	permission: expick.give
	permission message: &7&l[&4&lExPick&7&l] &cYou do not have the required permission to perform this command
	trigger:
		give diamond pickaxe with lore "&6Explosive 3x3x3" to arg-1

command ExpickToggle <text="false">:
	usage: /expicktoggle <true or false>
	permission: expick.toggle
	permission message: &7&l[&4&lExPick&7&l] &cYou do not have the required permission to perform this command
	trigger:
		if arg-1 is "false":
			set {enabled} to false
			message "&7&l[&4&lExPick&7&l] is toggled off"
		if arg-1 is "true":
			set {enabled} to true
			message "&7&l[&4&lExPick&7&l] is toggled on"

on load:
	set {blocks::*} to stone and andesite and diorite and granite and dirt and sandstone and netherrack and endstone and basalt and blackstone
	
on block break:
	if {enabled} is true:
		if player is holding a diamond pickaxe with lore "&6Explosive 3x3x3":
			loop blocks in radius 1.75 of event-block:
				if {blocks::*} contains loop-blocks:
					break loop-blocks naturally using player's tool
					add 1 to {uses.%player%}
				if {blocks::*} does not contain loop-blocks:
					cancel event
		if {uses.%player%} is {@EpickNotif1}:
			send action bar "&6Your Explosive Pickaxe will break soon!" to player
		if {uses.%player%} is {@EpickNotif2}:
			send action bar "&cYour Explosive Pickaxe will break very soon!" to player
		if {uses.%player%} is {@EpickMaxHealth}:
			set player's tool to air
			set {uses.%player%} to 0
			play sound "entity.item.break" with volume .75 to player
			send action bar "&4Your Explosive Pickaxe has broken!" to player
